apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: auditstore
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    value: daprauditfiles
  - name: storageAccessKey
  - name: container
    value: history